# Generated by Django 5.2.7 on 2025-10-10 16:38

import django.db.models.deletion
import sdr.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "raw_name",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        unique=True,
                        verbose_name="Raw name",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="Name"),
                ),
                (
                    "modulation",
                    models.CharField(max_length=255, verbose_name="Modulation"),
                ),
                (
                    "begin_frequency",
                    models.PositiveBigIntegerField(
                        db_index=True, verbose_name="Begin frequency"
                    ),
                ),
                (
                    "end_frequency",
                    models.PositiveBigIntegerField(
                        db_index=True, verbose_name="End frequency"
                    ),
                ),
                (
                    "data_type",
                    models.CharField(
                        default="audio", max_length=255, verbose_name="Data type"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AudioClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "subname",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Subname"
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "subname")},
            },
        ),
        migrations.CreateModel(
            name="Transmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "begin_frequency",
                    models.PositiveBigIntegerField(
                        db_index=True, verbose_name="Begin (frequency)"
                    ),
                ),
                (
                    "end_frequency",
                    models.PositiveBigIntegerField(
                        db_index=True, verbose_name="End (frequency)"
                    ),
                ),
                (
                    "begin_date",
                    models.DateTimeField(db_index=True, verbose_name="Begin (date)"),
                ),
                (
                    "end_date",
                    models.DateTimeField(db_index=True, verbose_name="End (date)"),
                ),
                (
                    "sample_size",
                    models.PositiveIntegerField(
                        db_index=True, verbose_name="Sample size"
                    ),
                ),
                (
                    "data_file",
                    models.FileField(
                        upload_to="transmission/%Y-%m-%d/", verbose_name="Data file"
                    ),
                ),
                (
                    "data_type",
                    models.CharField(max_length=255, verbose_name="Data type"),
                ),
                (
                    "audio_class",
                    models.ForeignKey(
                        default=sdr.models.get_default_audio_class_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sdr.audioclass",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        default=sdr.models.get_default_device_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sdr.device",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        default=sdr.models.get_default_group_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sdr.group",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Spectrogram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "begin_frequency",
                    models.PositiveBigIntegerField(
                        db_index=True, verbose_name="Begin (frequency)"
                    ),
                ),
                (
                    "end_frequency",
                    models.PositiveBigIntegerField(
                        db_index=True, verbose_name="End (frequency)"
                    ),
                ),
                (
                    "step_frequency",
                    models.PositiveIntegerField(
                        db_index=True, verbose_name="Step (frequency)"
                    ),
                ),
                (
                    "begin_model_date",
                    models.DateTimeField(db_index=True, verbose_name="Begin (model)"),
                ),
                (
                    "end_model_date",
                    models.DateTimeField(db_index=True, verbose_name="End (model)"),
                ),
                (
                    "begin_real_date",
                    models.DateTimeField(db_index=True, verbose_name="Begin (data)"),
                ),
                (
                    "end_real_date",
                    models.DateTimeField(db_index=True, verbose_name="End (data)"),
                ),
                ("labels", models.BinaryField(verbose_name="Labels")),
                (
                    "data_file",
                    models.FileField(
                        upload_to="spectrogram/%Y-%m-%d/", verbose_name="Data file"
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        default=sdr.models.get_default_device_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sdr.device",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    (
                        "device",
                        "begin_frequency",
                        "end_frequency",
                        "step_frequency",
                        "begin_model_date",
                        "end_model_date",
                    )
                },
            },
        ),
    ]
