# Generated by Django 5.2.7 on 2025-10-16 15:32

from django.db import migrations


def get_initial_groups(apps):
    Group = apps.get_model("sdr", "Group")
    return [
        Group(name="Airband", modulation="AM", begin_frequency=108000000, end_frequency=137000000),
        Group(name="Public services", modulation="FM", begin_frequency=137000000, end_frequency=174000000),
        Group(name="PMR 446", modulation="FM", begin_frequency=446000000, end_frequency=446200000),
        Group(name="Amateur radio 2200 m", modulation="FM", begin_frequency=135700, end_frequency=137800),
        Group(name="Amateur radio 630 m", modulation="FM", begin_frequency=472000, end_frequency=479000),
        Group(name="Amateur radio 160 m", modulation="FM", begin_frequency=1810000, end_frequency=2000000),
        Group(name="Amateur radio 80 m", modulation="FM", begin_frequency=3500000, end_frequency=3800000),
        Group(name="Amateur radio 40 m", modulation="FM", begin_frequency=7000000, end_frequency=7200000),
        Group(name="Amateur radio 30 m", modulation="FM", begin_frequency=10100000, end_frequency=10150000),
        Group(name="Amateur radio 20 m", modulation="FM", begin_frequency=14000000, end_frequency=14350000),
        Group(name="Amateur radio 17 m", modulation="FM", begin_frequency=18068000, end_frequency=18168000),
        Group(name="Amateur radio 15 m", modulation="FM", begin_frequency=21000000, end_frequency=21450000),
        Group(name="Amateur radio 12 m", modulation="FM", begin_frequency=24890000, end_frequency=24990000),
        Group(name="Amateur radio 10 m", modulation="FM", begin_frequency=28000000, end_frequency=29700000),
        Group(name="Amateur radio 6 m", modulation="FM", begin_frequency=50000000, end_frequency=52000000),
        Group(name="Amateur radio 4 m", modulation="FM", begin_frequency=70000000, end_frequency=70500000),
        Group(name="Amateur radio 2 m", modulation="FM", begin_frequency=144000000, end_frequency=146000000),
        Group(name="Amateur radio 70 cm", modulation="FM", begin_frequency=430000000, end_frequency=440000000),
        Group(name="Amateur radio 23 cm", modulation="FM", begin_frequency=1240000000, end_frequency=1300000000),
        Group(name="Amateur radio 13 cm", modulation="FM", begin_frequency=2320000000, end_frequency=2450000000),
        Group(name="Amateur radio 6 cm", modulation="FM", begin_frequency=5650000000, end_frequency=5850000000),
        Group(name="Amateur radio 3 cm", modulation="FM", begin_frequency=10000000000, end_frequency=10500000000),
        Group(name="Amateur radio 1.2 cm", modulation="FM", begin_frequency=24000000000, end_frequency=24250000000),
        Group(name="Amateur radio 6 mm", modulation="FM", begin_frequency=47000000000, end_frequency=47200000000),
        Group(name="Amateur radio 4 mm", modulation="FM", begin_frequency=76000000000, end_frequency=81000000000),
        Group(name="Amateur radio 2.4 mm", modulation="FM", begin_frequency=122250000000, end_frequency=123000000000),
        Group(name="Amateur radio 2 mm", modulation="FM", begin_frequency=134000000000, end_frequency=141000000000),
        Group(name="Amateur radio 1.2 mm", modulation="FM", begin_frequency=241000000000, end_frequency=250000000000),
    ]


def create_initial_groups(apps, schema_editor):
    Group = apps.get_model("sdr", "Group")
    Group.objects.bulk_create(get_initial_groups(apps))


def remove_initial_groups(apps, schema_editor):
    Group = apps.get_model("sdr", "Group")
    Group.objects.filter(name__in=[g.name for g in get_initial_groups(apps)]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("sdr", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_initial_groups, remove_initial_groups),
    ]
