# Generated by Django 5.2.7 on 2025-11-06 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sdr", "0003_raw_name_conversion"),
    ]

    operations = [
        migrations.CreateModel(
            name="GainTest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("device_prefix", models.CharField(max_length=255, verbose_name="Device prefix")),
                ("datetime", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
