# Generated by Django 5.2.7 on 2025-11-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sdr", "0004_gaintest"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=255, unique=True)),
                ("value", models.CharField(max_length=255)),
            ],
        ),
    ]
