# Generated by Django 5.2.7 on 2025-11-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sdr", "0005_appsetting"),
    ]

    operations = [
        migrations.AddField(
            model_name="spectrogram",
            name="source",
            field=models.CharField(
                default="scanner", max_length=255, verbose_name="Source"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transmission",
            name="name",
            field=models.CharField(default="auto", max_length=255, verbose_name="Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transmission",
            name="source",
            field=models.CharField(
                default="scanner", max_length=255, verbose_name="Source"
            ),
            preserve_default=False,
        ),
    ]
