# Generated by Django 5.2.7 on 2025-11-12 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdr', '0006_spectrogram_source_transmission_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audioclass',
            name='subname',
            field=models.CharField(max_length=255, verbose_name='Subname'),
        ),
    ]
