# Generated by Django 5.2.7 on 2025-11-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sdr", "0007_alter_audioclass_subname"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transmission",
            name="name",
        ),
        migrations.AlterField(
            model_name="group",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterUniqueTogether(
            name="group",
            unique_together={
                ("name", "modulation", "begin_frequency", "end_frequency")
            },
        ),
    ]
