# Generated by Django 5.2.7 on 2025-11-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sdr", "0008_alter_audioclass_subname"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="spectrogram",
            name="label",
        ),
        migrations.AddField(
            model_name="spectrogram",
            name="sample_nos",
            field=models.PositiveBigIntegerField(verbose_name="Samples count", db_index=True)
            ),
        migrations.AddField(
            model_name="spectrogram",
            name="labels_file",
            field=models.FileField(
                        upload_to="spectrogram/%Y-%m-%d/", verbose_name="Labels Data file"
                    ),
            ),
        
    ]
