# Generated by Django 6.0.1 on 2026-02-01 21:24

from django.db import migrations, models
import sdr.models
import sdr.utils.group


def update_transmissions(apps, schema_editor):
    Transmission = apps.get_model("sdr", "Transmission")
    Transmission.objects.filter(media_class="Noise").update(media_class="Unknown")
    Transmission.objects.filter(modulation="FM").update(modulation="NBFM")


def get_initial_groups(apps):
    Group = apps.get_model("sdr", "Group")
    return [
        Group(name="APRS", begin_frequency=144390000, end_frequency=144390000),
        Group(name="APRS", begin_frequency=144800000, end_frequency=144800000),
        Group(name="FM broadcast", begin_frequency=87500000, end_frequency=108000000),
    ]


def create_initial_groups(apps, schema_editor):
    Group = apps.get_model("sdr", "Group")
    Group.objects.bulk_create(get_initial_groups(apps))
    sdr.utils.group.update_groups()


def remove_initial_groups(apps, schema_editor):
    Group = apps.get_model("sdr", "Group")
    Group.objects.filter(name__in=[g.name for g in get_initial_groups(apps)]).delete()
    sdr.utils.group.update_groups()


class Migration(migrations.Migration):

    dependencies = [
        ("sdr", "0008_remove_transmission_name_alter_group_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transmission",
            name="media_class",
            field=models.CharField(
                default=sdr.models.get_default_media_class,
                max_length=255,
                verbose_name="Media class",
            ),
        ),
        migrations.AddField(
            model_name="transmission",
            name="modulation",
            field=models.CharField(
                default=sdr.models.get_default_modulation,
                max_length=255,
                verbose_name="Modulation",
            ),
        ),
        migrations.RunSQL(
            """
                UPDATE sdr_transmission
                SET modulation = (
                    SELECT modulation
                    FROM sdr_group
                    WHERE sdr_group.id = sdr_transmission.group_id
                );
            """
        ),
        migrations.RunSQL(
            """
                UPDATE sdr_transmission
                SET media_class = (
                    SELECT name
                    FROM sdr_audioclass
                    WHERE sdr_audioclass.id = sdr_transmission.audio_class_id
                );
            """
        ),
        migrations.RunPython(update_transmissions),
        migrations.RunSQL(
            """
            UPDATE sdr_transmission
            SET modulation = 'WBFM'
            WHERE (modulation = 'NBFM') and (75000 <= end_frequency - begin_frequency);
        """
        ),
        migrations.RemoveField(
            model_name="transmission",
            name="audio_class",
        ),
        migrations.RemoveField(
            model_name="transmission",
            name="data_type",
        ),
        migrations.DeleteModel(
            name="AudioClass",
        ),
        migrations.AlterUniqueTogether(
            name="group",
            unique_together={("name", "begin_frequency", "end_frequency")},
        ),
        migrations.RemoveField(
            model_name="group",
            name="data_type",
        ),
        migrations.RemoveField(
            model_name="group",
            name="modulation",
        ),
        migrations.RunPython(create_initial_groups, remove_initial_groups),
    ]
