# Generated by Django 6.0.1 on 2026-02-02 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sdr", "0009_remove_transmission_audio_class_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transmission",
            name="accuracy",
            field=models.FloatField(default=0.0, verbose_name="Accuracy"),
        ),
    ]
